# Generated by Django 4.1 on 2023-11-10 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_customuser_bio_remove_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
