version: '3'
services:
  postgre:
    container_name: db
    image: mysql
    restart: always
    networks:
      - bridge
    volumes:
     - db:/var/lib/mysql  # Adjusted for typical MariaDB data directory
     - ./postgre/tools/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    env_file:
      - .env

  backend:
    container_name: backend
    build: ./backend
    networks:
      - bridge
    volumes:
      -  backend:/usr/src/app
    env_file:
      - .env
    ports:
      - "3000:3000"

networks:
  bridge:
    driver: bridge

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: /Users/$USER/Desktop/transcendence/data/db
      o: bind
  backend:
    driver: local
    driver_opts:
      type: none
      device: /Users/$USER/Desktop/transcendence/data/backend
      o: bind
