version: '3'
services:
  postgre:
    container_name: db
    image: postgres:latest
    restart: always
    networks:
      - bridge
    volumes:
     - db:/var/lib/postgresql/data
     - ./postgre/tools:/docker-entrypoint-initdb.d
    env_file:
      - .env
    expose:
      - "5432"

  backend:
    container_name: backend
    build: ./backend
    restart: always
    networks:
      - bridge
    volumes:
      -  ./backend:/app
      -  /usr/src/app/node_modules
    env_file:
      - .env
    ports:
      - "5000:5000"

  frontend:
    container_name: frontend
    build: ./frontend
    #restart: always
    networks:
      - bridge
    volumes:
      #- ./frontend:/usr/src/app/src
      - ./frontend:/usr/share/nginx/html
      -  /usr/src/app/node_modules
    env_file:
      - .envFrontend
    ports:
      -  "80:80"
    depends_on:
      - backend
    #command: /bin/sh -c "while sleep 1000; do :; done"

networks:
  bridge:
    driver: bridge

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: /Users/$USER/Desktop/transcendence/src/data/postgre
      o: bind
  backend:
    driver: local
    driver_opts:
      type: none
      device: /Users/$USER/Desktop/transcendence/src/backend
      o: bind


#docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' backend