version: '3'
services:
  postgre:
    container_name: db
    image: postgres:latest
    restart: always
    networks:
      - bridge
    volumes:
     - db:/var/lib/postgresql/data
    env_file:
      - .env

  app:
    container_name: app
    build: ./app
    networks:
      - bridge
    volumes:
      -  app:/usr/src/app/src
      -  /usr/src/app/node_modules
    env_file:
      - .env
    ports:
      - "3000:3000"

networks:
  bridge:
    driver: bridge

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: /Users/ullorent/Desktop/transcendence/src/data/postgre
      o: bind
  app:
    driver: local
    driver_opts:
      type: none
      device: /Users/ullorent/Desktop/transcendence/src/app/backend
      o: bind
