version: '3'
services:
  postgre:
    container_name: db
    image: postgres:latest
    restart: always
    networks:
      - bridge
    volumes:
     - db:/var/lib/postgresql/data
     - ./postgre/tools:/docker-entrypoint-initdb.d
    env_file:
      - .env
    expose:
      - "5432"

  backend:
    container_name: backend
    build: ./backend
    restart: always
    networks:
      - bridge
    volumes:
      -  ./backend/server:/usr/src/app/src
      -  /usr/src/app/node_modules
    env_file:
      - .env
    ports:
      - "3000:3000"

  frontend:
    container_name: frontend
    build: ./frontend
    #restart: always
    networks:
      - bridge
    volumes:
      - ./frontend:/usr/src/app
      -  /usr/src/app/node_modules
      #- ./frontend/src:/usr/src/app/src
    env_file:
      - .env
    ports:
      -  "5173:5173"
    #command: /bin/sh -c "while sleep 1000; do :; done"


networks:
  bridge:
    driver: bridge

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: /Users/$USER/Desktop/transcendence/src/data/postgre
      o: bind
  backend:
    driver: local
    driver_opts:
      type: none
      device: /Users/$USER/Desktop/transcendence/src/backend
      o: bind